language: rust
rust:
  - stable
  - nightly

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

sudo: false

before_script:
  - cargo install cargo-travis
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo test

after_success:
  - cargo coveralls