[package]
name = "mpeg2ts-reader"
version = "0.1.0"
authors = ["David Holroyd <dave@badgers-in-foil.co.uk>"]
description = "Parser for MPEG Transport Stream data"
repository = "https://github.com/dholroyd/mpeg2ts-reader"
license = "MIT/Apache-2.0"

[dependencies]
hexdump = "0.1.0"
byteorder = "1.1.0"
data-encoding = "1.2.0"
crc = "1.0.0"
amphora = { git = "https://github.com/irauta/amphora.git" }
bitreader = { git = "https://github.com/irauta/bitreader.git" }
fixedbitset = "0.1.8"

[dev-dependencies]
matches = "0.1.6"
bitstream-io = "0.6.3"
criterion = "0.2"

[[bench]]
name = "bench"
harness = false

[profile.release]
# for profiling,
debug = true
