[package]
name = "mpeg2ts-reader"
version = "0.1.0"
authors = ["David Holroyd <dave@badgers-in-foil.co.uk>"]

[dependencies]
hexdump = "0.1.0"
byteorder = "1.1.0"
data-encoding = "1.2.0"
crc = "1.0.0"
