[package]
name = "mpeg2ts-reader-shootout"
version = "0.0.1"
publish = false

[dependencies]
mpeg2ts = "0.1.1"
mpeg2ts-reader = { path = ".." }
ffmpeg-sys = "3.4.1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false
